export enum Language {
  Hindi = "hindi",
  English = "english",
  Punjabi = "punjabi",
  Tamil = "tamil",
  Telugu = "telugu",
  Marathi = "marathi",
  Gujarati = "gujarati",
  Bengali = "bengali",
  Kannada = "kannada",
  Bhojpuri = "bhojpuri",
  Malayalam = "malayalam",
  Urdu = "urdu",
  Haryanvi = "haryanvi",
  Rajasthani = "rajasthani",
  Odia = "odia",
  Assamese = "assamese",
}
